[workspace]
members = [ "heapfull","zarlink"]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.81"
license = "MIT"
repository = "https://github.com/zeenix/zarlink/"

[profile.bench]
debug = true
strip = "none"
