[package]
name = "zarlink"
version = "0.1.0"
edition = "2021"

[features]
default = ["alloc"]
alloc = ["heapfull/alloc"]
heapless = ["heapfull/heapless"]

[dependencies]
heapfull = { path = "../heapfull" }
