[package]
name = "zlink-usb"
version = "0.0.1-alpha.1"
description = "USB-based transport for zlink"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
