[package]
name = "zlink-codegen"
version = "0.0.1-alpha.1"
description = "Utility to generate zlink code from varlink IDL files"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
