[package]
name = "zlink-micro"
version = "0.0.1-alpha.1"
description = "zlink library for microcontrollers"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
